

export interface ArtistData {
  id: number;
  nickname: string;
  email: string;
  city: string;
  street_address: string;
  randomImage: string;
}

const getRandomInt = (max: number) => Math.floor(Math.random() * max) + 1;

const artistdata: ArtistData[] = [
  {
    id: 1,
    nickname: "Randie",
    email: "rkleynen0@wsj.com",
    city: "Rongmei",
    street_address: "480 Talisman Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 2,
    nickname: "Audrey",
    email: "aslipper1@infoseek.co.jp",
    city: "Albarraque",
    street_address: "5509 Bashford Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 3,
    nickname: "Eadie",
    email: "ehaugeh2@nasa.gov",
    city: "Kaynardzha",
    street_address: "4 Prairieview Park",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 4,
    nickname: "Rahal",
    email: "rludovici3@4shared.com",
    city: "Santa Fe",
    street_address: "5947 Sunnyside Place",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 5,
    nickname: "Madlin",
    email: "maslott4@berkeley.edu",
    city: "Bandeirantes",
    street_address: "2944 Florence Street",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 6,
    nickname: "Hank",
    email: "hgodball5@prweb.com",
    city: "Liugong",
    street_address: "9 Summer Ridge Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 7,
    nickname: "Carmine",
    email: "ccrummy6@seesaa.net",
    city: "Gardanne",
    street_address: "434 Thompson Parkway",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 8,
    nickname: "Dino",
    email: "dzohrer7@sbwire.com",
    city: "Qinnan",
    street_address: "42 Dixon Alley",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 9,
    nickname: "Jobyna",
    email: "jchark8@a8.net",
    city: "Luotaping",
    street_address: "65351 Ryan Park",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 10,
    nickname: "Viv",
    email: "vsteeden9@prweb.com",
    city: "Bromma",
    street_address: "603 Gina Road",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 11,
    nickname: "Phillis",
    email: "pkeesa@netlog.com",
    city: "Malandag",
    street_address: "62398 Spaight Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 12,
    nickname: "Jamison",
    email: "jmacphersonb@bbc.co.uk",
    city: "Santa Cruz do Rio Pardo",
    street_address: "87608 Sauthoff Terrace",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 13,
    nickname: "Sapphira",
    email: "sallardycec@pcworld.com",
    city: "Samran",
    street_address: "49 Dunning Road",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 14,
    nickname: "Denny",
    email: "dpicotd@slashdot.org",
    city: "Peremyshl’",
    street_address: "559 Saint Paul Way",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 15,
    nickname: "Corney",
    email: "cglisenane@tripod.com",
    city: "Bourg-lès-Valence",
    street_address: "5820 Rieder Circle",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 16,
    nickname: "Laetitia",
    email: "lgummowf@bloglovin.com",
    city: "Huimin",
    street_address: "55568 Straubel Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 17,
    nickname: "Gretal",
    email: "grichfieldg@cyberchimps.com",
    city: "Jianxin",
    street_address: "614 Ryan Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 18,
    nickname: "Jenda",
    email: "jjeeh@macromedia.com",
    city: "Tríkeri",
    street_address: "2 Hermina Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 19,
    nickname: "Melonie",
    email: "mleathei@feedburner.com",
    city: "Leiden",
    street_address: "8676 Hazelcrest Junction",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 20,
    nickname: "Lydie",
    email: "lconantj@devhub.com",
    city: "Babakankiray",
    street_address: "9 Valley Edge Hill",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 21,
    nickname: "Shirlene",
    email: "smacgillk@wix.com",
    city: "São Vicente de Ferreira",
    street_address: "893 Morning Pass",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 22,
    nickname: "Cleveland",
    email: "covendonl@samsung.com",
    city: "Mandalasari",
    street_address: "1 Fisk Alley",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 23,
    nickname: "Scarlet",
    email: "sskillm@github.com",
    city: "Silvino Lobos",
    street_address: "9531 Hoepker Terrace",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 24,
    nickname: "Rasia",
    email: "rsoggn@paginegialle.it",
    city: "Niños Heroes",
    street_address: "47987 Petterle Place",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 25,
    nickname: "Allyce",
    email: "ajannawayo@google.co.jp",
    city: "Bobota",
    street_address: "246 Lerdahl Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 26,
    nickname: "Sosanna",
    email: "smilberryp@google.com",
    city: "Sundbyberg",
    street_address: "5 Pleasure Alley",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 27,
    nickname: "Cassaundra",
    email: "cfriftq@parallels.com",
    city: "Jabat",
    street_address: "56 Dwight Street",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 28,
    nickname: "Bradly",
    email: "blobr@reddit.com",
    city: "Helsingborg",
    street_address: "14633 Haas Terrace",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 29,
    nickname: "Nicolas",
    email: "nbrodways@wsj.com",
    city: "Irkliyevskaya",
    street_address: "69 Iowa Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 30,
    nickname: "Georgi",
    email: "gcoventryt@youtube.com",
    city: "Guamal",
    street_address: "71 Forster Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 31,
    nickname: "Randi",
    email: "rmaryottu@baidu.com",
    city: "Zemlyansk",
    street_address: "317 Rockefeller Avenue",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 32,
    nickname: "Genevieve",
    email: "glitzmannv@economist.com",
    city: "Huangyang",
    street_address: "8845 Crest Line Way",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 33,
    nickname: "Kippy",
    email: "kfiddyw@springer.com",
    city: "Tétouan",
    street_address: "987 Express Park",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 34,
    nickname: "Maggie",
    email: "msallowsx@unicef.org",
    city: "El Crucero",
    street_address: "8732 Rockefeller Crossing",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 35,
    nickname: "Ingrim",
    email: "icraty@answers.com",
    city: "Qidi",
    street_address: "3176 Anhalt Lane",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 36,
    nickname: "Ottilie",
    email: "oivaninz@wiley.com",
    city: "Boston",
    street_address: "5213 Everett Street",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 37,
    nickname: "Joannes",
    email: "jsinnott10@narod.ru",
    city: "Zouila",
    street_address: "671 Holmberg Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 38,
    nickname: "Raddie",
    email: "rharnell11@aboutads.info",
    city: "Haoshui",
    street_address: "004 Lotheville Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 39,
    nickname: "Else",
    email: "ebenduhn12@reddit.com",
    city: "Kos",
    street_address: "933 Springs Lane",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 40,
    nickname: "Izak",
    email: "iphilippe13@ebay.com",
    city: "Cuenca",
    street_address: "60483 Bunting Point",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 41,
    nickname: "Joey",
    email: "jdietzler14@netlog.com",
    city: "Los Angeles",
    street_address: "53160 Mesta Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 42,
    nickname: "Matthieu",
    email: "mveljes15@acquirethisname.com",
    city: "Smederevska Palanka",
    street_address: "8357 Pond Avenue",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 43,
    nickname: "Jolyn",
    email: "jcahan16@aboutads.info",
    city: "Yanjiang",
    street_address: "79 Eggendart Trail",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 44,
    nickname: "Ossie",
    email: "obraidley17@illinois.edu",
    city: "Oslo",
    street_address: "65 Eggendart Hill",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 45,
    nickname: "Cully",
    email: "cbedminster18@narod.ru",
    city: "Australia Square",
    street_address: "30047 Hoard Pass",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 46,
    nickname: "Lorne",
    email: "lravenscroftt19@imgur.com",
    city: "Bendungan",
    street_address: "4151 Sheridan Pass",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 47,
    nickname: "Evita",
    email: "ekidde1a@123-reg.co.uk",
    city: "Hobart",
    street_address: "65629 Arapahoe Trail",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 48,
    nickname: "Aggi",
    email: "akinnoch1b@japanpost.jp",
    city: "Hudiksvall",
    street_address: "02274 Wayridge Center",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 49,
    nickname: "Selby",
    email: "sglass1c@nbcnews.com",
    city: "Yashiro",
    street_address: "68218 Milwaukee Trail",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 50,
    nickname: "Pinchas",
    email: "psertin1d@dion.ne.jp",
    city: "Isnā",
    street_address: "545 Continental Street",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 51,
    nickname: "Simone",
    email: "sdegiovanni1e@twitpic.com",
    city: "Hamada",
    street_address: "85 Rockefeller Pass",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 52,
    nickname: "Pammie",
    email: "phuccaby1f@hao123.com",
    city: "Kālia",
    street_address: "665 Green Ridge Junction",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 53,
    nickname: "Chelsy",
    email: "cogormley1g@trellian.com",
    city: "Dahua",
    street_address: "19490 Towne Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 54,
    nickname: "Demott",
    email: "doddboy1h@artisteer.com",
    city: "Kolirerek",
    street_address: "3 Pankratz Circle",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 55,
    nickname: "Wynny",
    email: "wfallowes1i@zdnet.com",
    city: "Garko",
    street_address: "74 Walton Trail",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 56,
    nickname: "Ardelis",
    email: "awilloughway1j@merriam-webster.com",
    city: "Dahe",
    street_address: "48 Scoville Terrace",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 57,
    nickname: "Dexter",
    email: "dludee1k@instagram.com",
    city: "Sulahan",
    street_address: "9 Merry Way",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 58,
    nickname: "Clemente",
    email: "crosenblum1l@columbia.edu",
    city: "Kabankalan",
    street_address: "44579 Fremont Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 59,
    nickname: "Merrill",
    email: "mdudin1m@dedecms.com",
    city: "San Juan",
    street_address: "50 Vidon Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 60,
    nickname: "Aurea",
    email: "awildgoose1n@1und1.de",
    city: "Calabugao",
    street_address: "05992 West Junction",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 61,
    nickname: "Erik",
    email: "ecaveau1o@prlog.org",
    city: "Merapit",
    street_address: "0 Fairview Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 62,
    nickname: "Thurston",
    email: "tcraxford1p@walmart.com",
    city: "Futian",
    street_address: "26369 Holy Cross Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 63,
    nickname: "Doe",
    email: "dboswood1q@instagram.com",
    city: "Jaroměřice nad Rokytnou",
    street_address: "19291 Atwood Center",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 64,
    nickname: "Ellen",
    email: "ecarnalan1r@360.cn",
    city: "Pio",
    street_address: "75538 Delladonna Street",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 65,
    nickname: "Rutherford",
    email: "rjaimez1s@state.gov",
    city: "Getung",
    street_address: "142 Maple Alley",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 66,
    nickname: "Zonnya",
    email: "zcaselick1t@cocolog-nifty.com",
    city: "Starobachaty",
    street_address: "43538 Becker Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 67,
    nickname: "Felicia",
    email: "fpyburn1u@merriam-webster.com",
    city: "Derzhavīnsk",
    street_address: "24465 Badeau Lane",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 68,
    nickname: "Grove",
    email: "gostler1v@qq.com",
    city: "Al Majd",
    street_address: "527 Maple Wood Way",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 69,
    nickname: "Tracy",
    email: "theeron1w@purevolume.com",
    city: "Yug",
    street_address: "9383 2nd Place",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 70,
    nickname: "Giavani",
    email: "ghampshaw1x@digg.com",
    city: "Dschang",
    street_address: "05 Atwood Point",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 71,
    nickname: "Madalyn",
    email: "mbridges1y@ifeng.com",
    city: "Altunemil",
    street_address: "247 Dexter Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 72,
    nickname: "Carmon",
    email: "crissom1z@nhs.uk",
    city: "Yuanda",
    street_address: "2 Spaight Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 73,
    nickname: "Whit",
    email: "wgyurko20@bing.com",
    city: "Sindangsari",
    street_address: "916 Bay Center",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 74,
    nickname: "Humbert",
    email: "hcurrao21@parallels.com",
    city: "Arcena",
    street_address: "36 Vahlen Lane",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 75,
    nickname: "Salim",
    email: "sramstead22@cafepress.com",
    city: "Aimadamodo",
    street_address: "756 Hauk Parkway",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 76,
    nickname: "Tedman",
    email: "tfleckney23@tripod.com",
    city: "Duque de Caxias",
    street_address: "168 Rieder Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 77,
    nickname: "Ceciley",
    email: "cniess24@weebly.com",
    city: "Suncun",
    street_address: "61677 Merchant Road",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 78,
    nickname: "Valaria",
    email: "vancliff25@yelp.com",
    city: "Cibeureum",
    street_address: "404 Texas Hill",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 79,
    nickname: "Kaylyn",
    email: "kdorian26@meetup.com",
    city: "Podhum",
    street_address: "098 Sheridan Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 80,
    nickname: "Maryjo",
    email: "mdaskiewicz27@upenn.edu",
    city: "La Maná",
    street_address: "1 Cambridge Place",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 81,
    nickname: "Rafaello",
    email: "rsvanetti28@friendfeed.com",
    city: "Gaoqiao",
    street_address: "718 Sachtjen Point",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 82,
    nickname: "Maje",
    email: "mbravery29@amazon.de",
    city: "San Antonio",
    street_address: "36121 Ludington Circle",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 83,
    nickname: "Rosalinde",
    email: "rdombrell2a@shutterfly.com",
    city: "Józefów",
    street_address: "95 Mallory Park",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 84,
    nickname: "Neile",
    email: "ndjokovic2b@biblegateway.com",
    city: "Göteborg",
    street_address: "5 Bellgrove Place",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 85,
    nickname: "Bowie",
    email: "bscarlett2c@rakuten.co.jp",
    city: "Mahébourg",
    street_address: "7969 Morning Circle",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 86,
    nickname: "Robbie",
    email: "rortiga2d@xing.com",
    city: "Thāru Shāh",
    street_address: "998 North Road",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 87,
    nickname: "Anallese",
    email: "acopozio2e@lycos.com",
    city: "Dayuan",
    street_address: "9 Hoard Lane",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 88,
    nickname: "Pauline",
    email: "prosenzveig2f@w3.org",
    city: "Clorinda",
    street_address: "3 Tomscot Terrace",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 89,
    nickname: "Elladine",
    email: "epabel2g@nydailynews.com",
    city: "Salogon",
    street_address: "476 Moulton Point",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 90,
    nickname: "Marianne",
    email: "mhubbucke2h@acquirethisname.com",
    city: "Rābigh",
    street_address: "7 Sunbrook Lane",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 91,
    nickname: "Sollie",
    email: "smceniry2i@dell.com",
    city: "Basel",
    street_address: "15 Eastlawn Alley",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 92,
    nickname: "Annabell",
    email: "alippingwell2j@wunderground.com",
    city: "Gorobinci",
    street_address: "609 Michigan Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 93,
    nickname: "Alejandrina",
    email: "ahammatt2k@independent.co.uk",
    city: "Medvezh’yegorsk",
    street_address: "00 Larry Drive",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 94,
    nickname: "Ase",
    email: "amccloch2l@sciencedirect.com",
    city: "Bechlín",
    street_address: "2649 Hanson Court",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 95,
    nickname: "Adrienne",
    email: "ajacobovitz2m@desdev.cn",
    city: "Ljungbyholm",
    street_address: "4868 Hermina Way",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 96,
    nickname: "Essie",
    email: "edavydzenko2n@thetimes.co.uk",
    city: "Simenqian",
    street_address: "8190 Shopko Hill",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 97,
    nickname: "Othilia",
    email: "ohandy2o@php.net",
    city: "Iperó",
    street_address: "200 Claremont Plaza",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 98,
    nickname: "Honoria",
    email: "hgerleit2p@gov.uk",
    city: "Kudowa-Zdrój",
    street_address: "8283 Hazelcrest Hill",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 99,
    nickname: "Tanya",
    email: "tgooble2q@japanpost.jp",
    city: "Tongxing",
    street_address: "6057 Dwight Alley",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
  {
    id: 100,
    nickname: "Fina",
    email: "fchubb2r@java.com",
    city: "Yeroẖam",
    street_address: "8672 Crowley Way",
    randomImage: `https://picsum.photos/600/600?random=${getRandomInt(1000)}`,
  },
];

export default artistdata;
